services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fom_server
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - fom-server-database:/var/lib/mysql

  master-server:
    image: mcr.microsoft.com/dotnet/runtime:9.0
    platform: linux/amd64
    container_name: master-server
    depends_on:
      - db
    environment:
      Database__ConnectionString: "Host=db;Port=3306;Database=fom_server;Username=admin;Password=password;"
    ports:
      - "61001:61001/udp"
    volumes:
      - fom-server-build:/app
    working_dir: /app/publish/master
    command: ["dotnet", "MasterServer.dll"]
    restart: unless-stopped

  world-server:
    image: mcr.microsoft.com/dotnet/runtime:9.0
    platform: linux/amd64
    container_name: world-server
    depends_on:
      - db
      - master-server
    environment:
      Database__ConnectionString: "Host=db;Port=3306;Database=fom_server;Username=admin;Password=password;"
    ports:
      - "61002:61002/udp"
    volumes:
      - fom-server-build:/app
    working_dir: /app/publish/world
    command: ["dotnet", "WorldServer.dll"]
    restart: unless-stopped

volumes:
  fom-server-database:
    name: fom-server-database
  fom-server-build:
    name: fom-server-build
    external: true
