name: Setup Build Environment
description: Sets up the Docker containers that are required to build the project.

inputs:
  build-cache-dir:
    description: Directory for the C++ build cache
    required: true
  nuget-cache-dir:
    description: Directory for the NuGet cache
    required: true

runs:
  using: composite
  steps:
    - name: Prepare Docker
      uses: docker/setup-buildx-action@v3

    - name: Prepare Cache Directories
      shell: bash
      run: |
        mkdir -p ${{ inputs.build-cache-dir }}
        mkdir -p ${{ inputs.nuget-cache-dir }}

    - name: Cache Build Artifacts
      uses: actions/cache@v3
      with:
        path: ${{ inputs.build-cache-dir }}
        key: ${{ runner.os }}-build-${{ hashFiles(
          'fom-network/**/*.cpp',
          'fom-network/**/*.h',
          'extern/**/*.cpp',
          'extern/**/*.h',
          '**/CMakeLists.txt'
          ) }}
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Reset Cached Build File Timestamps
      shell: bash
      run: |
        if [ -d "${{ inputs.build-cache-dir }}" ]; then
          find "${{ inputs.build-cache-dir }}" -type f -exec touch {} + || true
        fi

    - name: Cache NuGet Packages
      uses: actions/cache@v3
      with:
        path: ${{ inputs.nuget-cache-dir }}
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Build C++ Docker Image
      uses: docker/build-push-action@v6
      with:
        context: docker/build
        file: docker/build/cpp.Dockerfile
        tags: fom/build-cpp
        load: true
        cache-from: type=gha,scope=cpp
        cache-to: type=gha,scope=cpp,mode=max

    - name: Build .NET Docker Image
      uses: docker/build-push-action@v6
      with:
        context: docker/build
        file: docker/build/dotnet.Dockerfile
        tags: fom/build-dotnet
        load: true
        cache-from: type=gha,scope=dotnet
        cache-to: type=gha,scope=dotnet,mode=max
