#pragma once

#include <fom-network/Common.h>

namespace FOMNetwork {

/* Type alias for player IDs. */
typedef uint32_t PlayerID_t;

/* Type alias for item IDs. */
typedef uint32_t ItemID_t;

/**
 * @enum WorldID
 *
 * The identifiers used for the different world servers in the game.
 */
enum WorldID : uint8_t {
  MASTER_SERVER = 0,
  NYC_MANHATTAN = 1,
  NYC_BROOKLYN = 2,
  TOKYO = 3,
  APARTMENTS = 4,
  TRAINING_GROUND = 5,
  NECARS_FIELD = 6,
  PARIS = 7,
  TESTING = 8,
  BERLIN = 9,
  UNUSED_WORLD = 10,
  ANDROMEDA_CITY = 11,
  // NEW_HAVEN = 12,
  // GANYMEDE = 13,
  DEMORGANS_CASTLE = 14,
  // KEPLERS_DOME = 15,
  // MOON_BASE = 16,
  // STS_GENESIS = 17,
  DSS_YUKON = 18,
  // BOOKERS_VALLEY = 19,
  // EPSILON_ERIDANI = 20,
  // TERRA_VENTURE_I = 21,
  // DOMINION_EXODUS = 22,
  // ESPEN_PARADISE = 23,
  // AQUATICA = 24,
  PEGASI_51 = 25,
  AURELIA = 26,
  PAX_PRIME = 27,
  CERES_DELTA = 28,
  TITAN_STATION = 29,
  CLONING_FACILITY = 30,
  NYC_GROUND_ZERO = 31,
  TRAINING_CENTER = 32,

  NUM_WORLDS = 33
};

/**
 * @enum Faction
 *
 * The identifiers used for the different factions in the game.
 */
enum Faction : uint8_t {
  INVALID_FACTION = 0,
  LED = 1,
  FDC = 2,
  GOM = 3,
  BOS = 4,
  MOTB = 5,
  CMG = 6,
  EC = 7,
  VI = 8,
  NUM_FACTIONS = 9
};

/**
 * @enum Faction
 *
 * The identifiers used for the different faction relations in the game.
 */
enum FactionRelation : uint8_t {
  INVALID_RELATION = 0,
  ALLY = 1,
  ECONOMIC_ALLY = 2,
  NEUTRAL = 3,
  ECONOMIC_ENEMY = 4,
  ENEMY = 5,
  NUM_RELATIONS = 6
};

/**
 * @enum ItemType
 *
 * The types for the items in the game.
 */
enum ItemType : uint16_t {
  ITEMTYPE_INVALID = 0,
};

#define NUM_WEAPON_SLOTS 3
#define NUM_QUICK_SLOTS 4

enum EquipmentSlots : uint8_t {
  SLOT_HEAD = 0,
  SLOT_FACE = 1,
  SLOT_SHOULDER = 2,
  SLOT_CHEST = 3,
  SLOT_ARMS = 4,
  SLOT_HANDS = 5,
  SLOT_LEGS = 6,
  SLOT_BACK = 7,
  SLOT_HAT = 8,
  SLOT_SHIRT = 9,
  SLOT_BOTTOMS = 10,
  SLOT_SHOES = 11,
  NUM_EQUIPMENT_SLOTS = 12
};

enum PlayerAttributeTypes : uint8_t {
  ATTRIBUTE_HEALTH = 0,
  ATTRIBUTE_STAMINA = 1,
  ATTRIBUTE_BIOENERGY = 2,
  ATTRIBUTE_AURA = 3,
  ATTRIBUTE_CREDITS = 4,
  ATTRIBUTE_FACTION_CREDITS = 5,
  ATTRIBUTE_EXPERIENCE_POINTS = 6,
  ATTRIBUTE_PENALTY_POINTS = 7,
  ATTRIBUTE_AVAILABLE_CLONES = 8,
  ATTRIBUTE_PRISONER = 9,
  ATTRIBUTE_FACTION_PRIVILEGES = 10,
  ATTRIBUTE_BOOSTER_1 = 11,
  ATTRIBUTE_BOOSTER_2 = 12,
  ATTRIBUTE_BOOSTER_3 = 13,
  ATTRIBUTE_SENATOR = 14,
  ATTRIBUTE_MOST_WANTED = 15,
  ATTRIBUTE_FUGITIVE = 16,
  ATTRIBUTE_AGILITY = 17,
  ATTRIBUTE_BALLISTIC_DAMAGE = 18,
  ATTRIBUTE_ENERGY_DAMAGE = 19,
  ATTRIBUTE_STAMINA_DAMAGE = 20,
  ATTRIBUTE_BIOENERGY_DAMAGE = 21,
  ATTRIBUTE_AURA_DAMAGE = 22,
  ATTRIBUTE_DESTRUCTION = 23,
  ATTRIBUTE_WEAPON_RECOIL = 24,
  ATTRIBUTE_ARMOR = 25,
  ATTRIBUTE_PROTECTION_REDUCTION = 26,
  ATTRIBUTE_SHIELDING = 27,
  ATTRIBUTE_ENDURANCE = 28,
  ATTRIBUTE_RESISTANCE = 29,
  ATTRIBUTE_REFLECTION = 30,
  ATTRIBUTE_DEFENSE_RATING = 31,
  ATTRIBUTE_BLOCK_RATING = 32,
  ATTRIBUTE_CRIT_RATING = 33,
  ATTRIBUTE_HEALTH_REGEN = 34,
  ATTRIBUTE_STAMINA_REGEN = 35,
  ATTRIBUTE_BIOENERGY_REGEN = 36,
  ATTRIBUTE_AURA_REGEN = 37,
  ATTRIBUTE_ADDICTION = 38,
  ATTRIBUTE_ADDICTION_TREATMENT = 39,
  ATTRIBUTE_COINS = 40,
  ATTRIBUTE_DRUG_COOLDOWN = 41,
  ATTRIBUTE_FOOD_COOLDOWN = 42,
  ATTRIBUTE_XENO_DAMAGE = 43,
  ATTRIBUTE_HEALTH_DRAIN = 44,
  ATTRIBUTE_STAMINA_DRAIN = 45,
  ATTRIBUTE_BIOENERGY_DRAIN = 46,
  ATTRIBUTE_AURA_LOSS = 47,
  ATTRIBUTE_MEDIKIT_COOLDOWN = 48,
  NUM_ATTRIBUTES = 49
};

}  // namespace FOMNetwork
