#pragma once

#include <fom-network/InteropTypes.h>

namespace FOMNetwork {
namespace Enum {

enum ApartmentType : uint8_t {
  APARTMENT_INVALID = 0,
  APARTMENT_CITY_FLAT = 1,
  APARTMENT_RATHOLE = 2,
  APARTMENT_COLONIAL_FLAT = 3,
  APARTMENT_FRENCH_FLAT = 4,
  APARTMENT_JAPANESE_FLAT = 5,
  APARTMENT_UNDERWATER_FLAT = 6,
  APARTMENT_CITY_APARTMENT = 7,
  APARTMENT_CELLAR = 8,
  APARTMENT_COLONIAL_APARTMENT = 9,
  APARTMENT_FRENCH_APARTMENT = 10,
  APARTMENT_JAPANESE_APARTMENT = 11,
  APARTMENT_UNDERWATER_APARTMENT = 12,
  APARTMENT_CITY_SUITE = 13,
  APARTMENT_RAMSHACKLE_HUT = 14,
  APARTMENT_COLONIAL_SUITE = 15,
  APARTMENT_FRENCH_PENTHOUSE = 16,
  APARTMENT_JAPANESE_PENTHOUSE = 17,
  APARTMENT_UNDERWATER_SUITE = 18,
  APARTMENT_UNDERGROUND_HQ = 19,
  APARTMENT_TACTICAL_HQ = 20,
  APARTMENT_CITY_TOWER_OFFICES = 21,
  APARTMENT_ARCTURUS_FREIGHTER = 22,
  APARTMENT_PRISON_DUEL_ARENA = 23,
  APARTMENT_BACKER_SAFEHOUSE = 24,
};

}  // namespace Enum
}  // namespace FOMNetwork
