#pragma once

#include <fom-network/InteropTypes.h>

namespace FOMNetwork {
namespace Enum {

enum AttributeType : uint8_t {
  ATTRIBUTE_HEALTH = 0,
  ATTRIBUTE_STAMINA = 1,
  ATTRIBUTE_BIO_ENERGY = 2,
  ATTRIBUTE_AURA = 3,
  ATTRIBUTE_UNIVERSAL_CREDITS = 4,
  ATTRIBUTE_FACTION_CREDITS = 5,
  ATTRIBUTE_PENALTY = 6,
  ATTRIBUTE_PRISONER_STATUS = 7,
  ATTRIBUTE_HIGHEST_PENALTY = 8,
  ATTRIBUTE_MOST_WANTED_STATUS = 9,
  ATTRIBUTE_WANTED_STATUS = 10,
  ATTRIBUTE_AGILITY = 11,
  ATTRIBUTE_BALLISTIC_DAMAGE = 12,
  ATTRIBUTE_ENERGY_DAMAGE = 13,
  ATTRIBUTE_BIO_DAMAGE = 14,
  ATTRIBUTE_AURA_DAMAGE = 15,
  ATTRIBUTE_DESTRUCTION = 16,
  ATTRIBUTE_WEAPON_RECOIL = 17,
  ATTRIBUTE_ARMOR = 18,
  ATTRIBUTE_SHIELDING = 19,
  ATTRIBUTE_RESISTANCE = 20,
  ATTRIBUTE_REFLECTION = 21,
  ATTRIBUTE_HEALTH_REGENERATION = 22,
  ATTRIBUTE_STAMINA_REGENERATION = 23,
  ATTRIBUTE_BIO_REGENERATION = 24,
  ATTRIBUTE_AURA_REGENERATION = 25,
  ATTRIBUTE_COINS = 26,
  ATTRIBUTE_HEALING_COOLDOWN = 27,
  ATTRIBUTE_FOOD_COOLDOWN = 28,
  ATTRIBUTE_XENO_DAMAGE = 29,
  ATTRIBUTE_HEALTH_DRAIN = 30,
  ATTRIBUTE_STAMINA_DRAIN = 31,
  ATTRIBUTE_BIO_ENERGY_DRAIN = 32,
  ATTRIBUTE_AURA_DRAIN = 33,
  ATTRIBUTE_PROTECTION_BYPASS = 34,
  ATTRIBUTE_EFFECTIVE_RANGE = 35,
  ATTRIBUTE_WEAPON_FIRE_DELAY = 36,
  // 37
  // 38
  ATTRIBUTE_WEIGHT = 39,
  ATTRIBUTE_JUMP_VELOCITY_MULTIPLIER = 40,
  ATTRIBUTE_FALL_DAMAGE_MULTIPLIER = 41,
  ATTRIBUTE_NIGHTVISION = 42,
  ATTRIBUTE_SOUNDLESS_MOVEMENT = 43,
  ATTRIBUTE_ACTIVATION_DISTANCE = 44,
  ATTRIBUTE_SPRINT_SPEED_MULTIPLIER = 45,
  ATTRIBUTE_MAX_STAMINA = 46,
  ATTRIBUTE_BIO_ENERGY_REPLENISHING_COOLDOWN = 47,
  ATTRIBUTE_AURA_HEALING_COOLDOWN = 48,
  ATTRIBUTE_EMERGENCY_SHIELD = 49,
  ATTRIBUTE_EMERGENCY_SHIELD_COOLDOWN = 50,
  ATTRIBUTE_VORTEX_EMITTER_COUNTDOWN = 51,
  // 52

  NUM_ATTRIBUTE_TYPES = 53
};

}  // namespace Enum
}  // namespace FOMNetwork
