services:
  cpp-build:
    platform: linux/amd64
    build:
      context: ./cpp
      dockerfile: Dockerfile
    volumes:
      - ../../:/src:ro          # mount source read-only
      - ../../out/docker/linux:/out          # mount shared out directory
    working_dir: /src
    entrypoint: ["/bin/bash"]
    tty: true
    stdin_open: true

  dotnet-build:
    platform: linux/amd64
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    environment:
      - FOMServerBuildEnvironment=Docker
    volumes:
      - ../../:/src:ro
      - ../../out/docker/linux:/out
    working_dir: /src
    entrypoint: ["/bin/bash"]
    tty: true
    stdin_open: true
